# Generated by Django 6.0.6 on 2026-06-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('imagen', models.ImageField(upload_to='capturas/')),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
