# Generated by Django 6.0.6 on 2026-06-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffereporte',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='coffereporte',
            name='imagen',
        ),
        migrations.AddField(
            model_name='coffereporte',
            name='csv',
            field=models.FileField(default='', upload_to='csv/'),
            preserve_default=False,
        ),
    ]
